name: Slack build status

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  buildstate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install slack-sdk

      - name: Run status script
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: python goatsBuildState.py
